sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "4"
matrix:
  allow_failures:
    - node_js:
      - "0.11"
      - "iojs-1"
      - "iojs-2"
      - "iojs-3"
